export const categories = [
    {
        id:"1",
        image:"/lady.jpg",
        title:"Women's"
    },
    {
        id:"2",
        image:"/mens.jpg",
        title:"Men's"
    },
    {
        id:"3",
        image:"camera.avif",
        title:"Camera"
    },
    {
        id:"4",
        image:"shoes.webp",
        title:"Shoes"
    },
]